In [3]:
%pip install yfinance

Collecting yfinance
  Using cached yfinance-1.7.0-py3-none-any.whl.metadata (6.7 kB)
Requirement already satisfied: beautifulsoup4>=4.11.1 in c:\Users\lynst\anaconda3\envs\azure_ml\Lib\site-packages (from yfinance) (4.15.0)
Collecting curl_cffi>=0.15 (from yfinance)
  Downloading curl_cffi-0.16.3-cp310-abi3-win_amd64.whl.metadata (17 kB)
Collecting lxml>=4.9.0 (from yfinance)
  Downloading lxml-6.1.3-cp312-cp312-win_amd64.whl.metadata (3.4 kB)
Collecting multitasking>=0.0.7 (from yfinance)
  Using cached multitasking-0.0.13-py3-none-any.whl.metadata (16 kB)
Requirement already satisfied: numpy>=1.16.5 in c:\Users\lynst\anaconda3\envs\azure_ml\Lib\site-packages (from yfinance) (1.26.4)
Requirement already satisfied: pandas>=1.3.0 in c:\Users\lynst\anaconda3\envs\azure_ml\Lib\site-packages (from yfinance) (2.2.3)
Collecting peewee>=3.16.2 (from yfinance)
  Downloading peewee-4.5.1-py3-none-any.whl.metadata (10 kB)
Requirement already satisfied: platformdirs>=2.0.0 in c:\Users\lynst\anaconda3\envs\azure_ml\Lib\site-packages (from yfinance) (4.9.4)
Requirement already satisfied: protobuf>=3.19.0 in c:\Users\lynst\anaconda3\envs\azure_ml\Lib\site-packages (from yfinance) (6.33.5)
Requirement already satisfied: pytz>=2022.5 in c:\Users\lynst\anaconda3\envs\azure_ml\Lib\site-packages (from yfinance) (2025.2)
Requirement already satisfied: requests>=2.31 in c:\Users\lynst\anaconda3\envs\azure_ml\Lib\site-packages (from yfinance) (2.32.5)
Requirement already satisfied: websockets>=13.0 in c:\Users\lynst\anaconda3\envs\azure_ml\Lib\site-packages (from yfinance) (16.0)
Requirement already satisfied: soupsieve>=1.6.1 in c:\Users\lynst\anaconda3\envs\azure_ml\Lib\site-packages (from beautifulsoup4>=4.11.1->yfinance) (2.5)
Requirement already satisfied: typing-extensions>=4.0.0 in c:\Users\lynst\anaconda3\envs\azure_ml\Lib\site-packages (from beautifulsoup4>=4.11.1->yfinance) (4.15.0)
Requirement already satisfied: cffi>=2.0.0 in c:\Users\lynst\anaconda3\envs\azure_ml\Lib\site-packages (from curl_cffi>=0.15->yfinance) (2.0.0)
Requirement already satisfied: certifi>=2024.2.2 in c:\Users\lynst\anaconda3\envs\azure_ml\Lib\site-packages (from curl_cffi>=0.15->yfinance) (2026.2.25)
Requirement already satisfied: pycparser in c:\Users\lynst\anaconda3\envs\azure_ml\Lib\site-packages (from cffi>=2.0.0->curl_cffi>=0.15->yfinance) (2.23)
Requirement already satisfied: python-dateutil>=2.8.2 in c:\Users\lynst\anaconda3\envs\azure_ml\Lib\site-packages (from pandas>=1.3.0->yfinance) (2.9.0.post0)
Requirement already satisfied: tzdata>=2022.7 in c:\Users\lynst\anaconda3\envs\azure_ml\Lib\site-packages (from pandas>=1.3.0->yfinance) (2025.3)
Requirement already satisfied: six>=1.5 in c:\Users\lynst\anaconda3\envs\azure_ml\Lib\site-packages (from python-dateutil>=2.8.2->pandas>=1.3.0->yfinance) (1.17.0)
Requirement already satisfied: charset_normalizer<4,>=2 in c:\Users\lynst\anaconda3\envs\azure_ml\Lib\site-packages (from requests>=2.31->yfinance) (3.4.4)
Requirement already satisfied: idna<4,>=2.5 in c:\Users\lynst\anaconda3\envs\azure_ml\Lib\site-packages (from requests>=2.31->yfinance) (3.11)
Requirement already satisfied: urllib3<3,>=1.21.1 in c:\Users\lynst\anaconda3\envs\azure_ml\Lib\site-packages (from requests>=2.31->yfinance) (2.6.3)
Using cached yfinance-1.7.0-py3-none-any.whl (149 kB)
Downloading curl_cffi-0.16.3-cp310-abi3-win_amd64.whl (2.0 MB)
   ---------------------------------------- 0.0/2.0 MB ? eta -:--:--
   ----- ---------------------------------- 0.3/2.0 MB ? eta -:--:--
   ---------- ----------------------------- 0.5/2.0 MB 1.5 MB/s eta 0:00:01
   --------------- ------------------------ 0.8/2.0 MB 1.5 MB/s eta 0:00:01
   --------------------- ------------------ 1.0/2.0 MB 1.5 MB/s eta 0:00:01
   -------------------------- ------------- 1.3/2.0 MB 1.5 MB/s eta 0:00:01
   ------------------------------------- -- 1.8/2.0 MB 1.5 MB/s eta 0:00:01
   ---------------------------------------- 2.0/2.0 MB 1.4 MB/s  0:00:01
Downloading lxml-6.1.3-cp312-cp312-win_amd64.whl (4.0 MB)
   ---------------------------------------- 0.0/4.0 MB ? eta -:--:--
   -- ------------------------------------- 0.3/4.0 MB ? eta -:--:--
   ----- ---------------------------------- 0.5/4.0 MB 1.4 MB/s eta 0:00:03
   ------- -------------------------------- 0.8/4.0 MB 1.5 MB/s eta 0:00:03
   ---------- ----------------------------- 1.0/4.0 MB 1.4 MB/s eta 0:00:03
   --------------- ------------------------ 1.6/4.0 MB 1.4 MB/s eta 0:00:02
   ------------------ --------------------- 1.8/4.0 MB 1.4 MB/s eta 0:00:02
   -------------------- ------------------- 2.1/4.0 MB 1.5 MB/s eta 0:00:02
   ----------------------- ---------------- 2.4/4.0 MB 1.4 MB/s eta 0:00:02
   -------------------------- ------------- 2.6/4.0 MB 1.4 MB/s eta 0:00:01
   ------------------------------- -------- 3.1/4.0 MB 1.4 MB/s eta 0:00:01
   ---------------------------------- ----- 3.4/4.0 MB 1.4 MB/s eta 0:00:01
   ------------------------------------ --- 3.7/4.0 MB 1.4 MB/s eta 0:00:01
   ---------------------------------------- 4.0/4.0 MB 1.4 MB/s  0:00:02
Using cached multitasking-0.0.13-py3-none-any.whl (16 kB)
Downloading peewee-4.5.1-py3-none-any.whl (193 kB)
Installing collected packages: multitasking, peewee, lxml, curl_cffi, yfinance

   -------- ------------------------------- 1/5 [peewee]
   -------- ------------------------------- 1/5 [peewee]
   -------- ------------------------------- 1/5 [peewee]
   ---------------- ----------------------- 2/5 [lxml]
   ---------------- ----------------------- 2/5 [lxml]
   ---------------- ----------------------- 2/5 [lxml]
   ------------------------ --------------- 3/5 [curl_cffi]
   ------------------------ --------------- 3/5 [curl_cffi]
   ------------------------ --------------- 3/5 [curl_cffi]
   -------------------------------- ------- 4/5 [yfinance]
   -------------------------------- ------- 4/5 [yfinance]
   -------------------------------- ------- 4/5 [yfinance]
   ---------------------------------------- 5/5 [yfinance]

Successfully installed curl_cffi-0.16.3 lxml-6.1.3 multitasking-0.0.13 peewee-4.5.1 yfinance-1.7.0
Note: you may need to restart the kernel to use updated packages.

In [4]:
import yfinance as yf

msft = yf.Ticker("MSFT")
print(msft)

yfinance.Ticker object <MSFT>

In [5]:
# get stock info
msft.info

{'address1': 'One Microsoft Way',
 'city': 'Redmond',
 'state': 'WA',
 'zip': '98052-6399',
 'country': 'United States',
 'phone': '425 882 8080',
 'website': 'https://www.microsoft.com',
 'industry': 'Software - Infrastructure',
 'industryKey': 'software-infrastructure',
 'industryDisp': 'Software - Infrastructure',
 'sector': 'Technology',
 'sectorKey': 'technology',
 'sectorDisp': 'Technology',
 'longBusinessSummary': "Microsoft Corporation, a technology company, develops and supports a portfolio of technology solutions for individuals and businesses worldwide. Its products include operating systems, server applications, business solution applications, software development tools, desktop and server management tools, and video games; and devices, such as PCs, tablets, gaming and entertainment consoles, other intelligent devices, and related accessories. The company's Productivity and Business Processes segment offers Microsoft 365 Commercial, Enterprise Mobility + Security, Power BI, Exchange, SharePoint, Microsoft Teams, Microsoft 365 Security and Compliance, Microsoft 365 Copilot, and Windows Commercial on-premises and Office licensed on-premises. This segment also provides Microsoft 365 Consumer products and cloud services; LinkedIn, including talent solutions, marketing solutions, subscriptions, and sales solutions; Dynamics 365, a set of cloud-based applications; and on-premises ERP and CRM applications. Its Intelligent Cloud segment offers server products and cloud services; cloud and AI consumption-based services, GitHub cloud services, health and life sciences cloud services, as well as virtual desktop offerings, and other cloud services; SQL Server, Windows Server, Visual Studio, System Center, and related client access licenses; and enterprise support services, industry solutions, Microsoft partner network, and learning experience. The company's More Personal Computing segment provides Windows OEM licensing and devices comprising Surface and PC accessories; XBOX hardware, and XBOX first- and third-party content and services; XBOX Game Pass and other subscriptions; XBOX Cloud Gaming, advertising, and other cloud services; and search advertising consisting of Bing, Copilot, Microsoft News, Microsoft Edge, and third-party affiliates. It sells its products through partners and retail networks. The company was founded in 1975 and is headquartered in Redmond, Washington.",
 'fullTimeEmployees': 223000,
 'companyOfficers': [{'maxAge': 1,
   'name': 'Mr. Satya  Nadella',
   'age': 58,
   'title': 'Chairman & CEO',
   'yearBorn': 1967,
   'fiscalYear': 2025,
   'totalPay': 12251294,
   'exercisedValue': 0,
   'unexercisedValue': 0},
  {'maxAge': 1,
   'name': 'Mr. Bradford L. Smith LCA',
   'age': 66,
   'title': 'President & Vice Chairman',
   'yearBorn': 1959,
   'fiscalYear': 2025,
   'totalPay': 4532750,
   'exercisedValue': 0,
   'unexercisedValue': 0},
  {'maxAge': 1,
   'name': 'Ms. Amy E. Hood',
   'age': 53,
   'title': 'Executive VP & CFO',
   'yearBorn': 1972,
   'fiscalYear': 2025,
   'totalPay': 4444191,
   'exercisedValue': 0,
   'unexercisedValue': 0},
  {'maxAge': 1,
   'name': 'Mr. Takeshi  Numoto',
   'age': 54,
   'title': 'Executive VP & Chief Marketing Officer',
   'yearBorn': 1971,
   'fiscalYear': 2025,
   'totalPay': 2871250,
   'exercisedValue': 0,
   'unexercisedValue': 0},
  {'maxAge': 1,
   'name': 'Mr. Judson B. Althoff',
   'age': 52,
   'title': 'Executive VP & CEO of Commercial Business',
   'yearBorn': 1973,
   'fiscalYear': 2025,
   'totalPay': 4490115,
   'exercisedValue': 0,
   'unexercisedValue': 0},
  {'maxAge': 1,
   'name': 'Ms. Carolina  Dybeck Happe',
   'age': 53,
   'title': 'Executive VP & COO',
   'yearBorn': 1972,
   'fiscalYear': 2025,
   'exercisedValue': 0,
   'unexercisedValue': 0},
  {'maxAge': 1,
   'name': 'Ms. Alice L. Jolla',
   'age': 59,
   'title': 'Corporate VP & Chief Accounting Officer',
   'yearBorn': 1966,
   'fiscalYear': 2025,
   'exercisedValue': 0,
   'unexercisedValue': 0},
  {'maxAge': 1,
   'name': 'Mr. Matthew  Kerner',
   'title': 'CTO & Corporate VP of Worldwide Sales and Solutions',
   'fiscalYear': 2025,
   'exercisedValue': 0,
   'unexercisedValue': 0},
  {'maxAge': 1,
   'name': 'Jonathan  Neilson',
   'title': 'Vice President of Investor Relations',
   'fiscalYear': 2025,
   'exercisedValue': 0,
   'unexercisedValue': 0},
  {'maxAge': 1,
   'name': 'Mr. Jonathan M. Palmer',
   'title': 'Corporate Vice President & Chief Legal Officer',
   'fiscalYear': 2025,
   'exercisedValue': 0,
   'unexercisedValue': 0}],
 'auditRisk': 9,
 'boardRisk': 7,
 'compensationRisk': 5,
 'shareHolderRightsRisk': 2,
 'overallRisk': 5,
 'governanceEpochDate': 1788220800,
 'compensationAsOfEpochDate': 1767139200,
 'irWebsite': 'http://www.microsoft.com/investor/default.aspx',
 'executiveTeam': [],
 'maxAge': 86400,
 'priceHint': 2,
 'previousClose': 492.44,
 'open': 495.625,
 'dayLow': 492.58,
 'dayHigh': 498.97,
 'regularMarketPreviousClose': 492.44,
 'regularMarketOpen': 495.625,
 'regularMarketDayLow': 492.58,
 'regularMarketDayHigh': 498.97,
 'dividendRate': 3.64,
 'dividendYield': 0.73,
 'exDividendDate': 1787184000,
 'payoutRatio': 0.1983,
 'fiveYearAvgDividendYield': 0.79,
 'beta': 1.108,
 'trailingPE': 27.62709,
 'forwardPE': 21.025343,
 'volume': 14518435,
 'regularMarketVolume': 14518435,
 'averageVolume': 35445946,
 'averageVolume10days': 19734810,
 'averageDailyVolume10Day': 19734810,
 'bid': 495.53,
 'ask': 510.0,
 'bidSize': 4,
 'askSize': 1,
 'marketCap': 3680323239936,
 'nonDilutedMarketCap': 3680323111704,
 'fiftyTwoWeekLow': 349.2,
 'fiftyTwoWeekHigh': 553.72,
 'allTimeHigh': 555.45,
 'allTimeLow': 0.088542,
 'fulldayPrice': 494.89,
 'fulldayChange': 3.1900024,
 'fulldayChangePercent': 0.64779514,
 'priceToSalesTrailing12Months': 11.090689,
 'fiftyDayAverage': 453.6688,
 'twoHundredDayAverage': 431.25754,
 'trailingAnnualDividendRate': 3.64,
 'trailingAnnualDividendYield': 0.007391764,
 'currency': 'USD',
 'tradeable': False,
 'enterpriseValue': 3732293025792,
 'profitMargins': 0.40305,
 'floatShares': 7414407173,
 'sharesOutstanding': 7425545491,
 'sharesShort': 74451155,
 'sharesShortPriorMonth': 81311791,
 'sharesShortPreviousMonthDate': 1785456000,
 'dateShortInterest': 1788134400,
 'sharesPercentSharesOut': 0.01,
 'heldPercentInsiders': 0.00091,
 'heldPercentInstitutions': 0.75792,
 'shortRatio': 2.49,
 'shortPercentOfFloat': 0.01,
 'impliedSharesOutstanding': 7425545491,
 'bookValue': 59.565,
 'priceToBook': 8.320827,
 'lastFiscalYearEnd': 1782777600,
 'nextFiscalYearEnd': 1814313600,
 'mostRecentQuarter': 1782777600,
 'earningsQuarterlyGrowth': 0.313,
 'netIncomeToCommon': 133748998144,
 'trailingEps': 17.94,
 'forwardEps': 23.57298,
 'pegRatio': 1.61,
 'lastSplitFactor': '2:1',
 'lastSplitDate': 1045526400,
 'enterpriseToRevenue': 11.247,
 'enterpriseToEbitda': 19.215,
 '52WeekChange': -0.038283944,
 'SandP52WeekChange': 0.1574688,
 'lastDividendValue': 0.91,
 'lastDividendDate': 1787184000,
 'quoteType': 'EQUITY',
 'currentPrice': 495.63,
 'targetHighPrice': 870.0,
 'targetLowPrice': 400.0,
 'targetMeanPrice': 572.91516,
 'targetMedianPrice': 555.0,
 'recommendationMean': 1.36364,
 'recommendationKey': 'strong_buy',
 'numberOfAnalystOpinions': 52,
 'totalCash': 76842999808,
 'totalCashPerShare': 10.348,
 'ebitda': 194237005824,
 'totalDebt': 128812998656,
 'quickRatio': 1.099,
 'currentRatio': 1.23,
 'totalRevenue': 331839012864,
 'debtToEquity': 29.118,
 'revenuePerShare': 44.668,
 'returnOnAssets': 0.14088,
 'returnOnEquity': 0.34039003,
 'grossProfits': 225465008128,
 'freeCashflow': 16545500160,
 'operatingCashflow': 182934994944,
 'earningsGrowth': 0.317,
 'revenueGrowth': 0.177,
 'grossMargins': 0.67944,
 'ebitdaMargins': 0.58534,
 'operatingMargins': 0.45111,
 'financialCurrency': 'USD',
 'symbol': 'MSFT',
 'language': 'en-US',
 'region': 'US',
 'typeDisp': 'Equity',
 'quoteSourceName': 'Delayed Quote',
 'triggerable': True,
 'customPriceAlertConfidence': 'HIGH',
 'marketState': 'CLOSED',
 'cryptoTradeable': False,
 'hasPrePostMarketData': True,
 'firstTradeDateMilliseconds': 511108200000,
 'postMarketChangePercent': -0.14930296,
 'postMarketPrice': 494.89,
 'postMarketChange': -0.73999023,
 'regularMarketChange': 3.1900024,
 'regularMarketDayRange': '492.58 - 498.97',
 'fullExchangeName': 'NasdaqGS',
 'averageDailyVolume3Month': 35445946,
 'exchange': 'NMS',
 'messageBoardId': 'finmb_21835',
 'exchangeTimezoneName': 'America/New_York',
 'exchangeTimezoneShortName': 'EDT',
 'gmtOffSetMilliseconds': -14400000,
 'market': 'us_market',
 'esgPopulated': False,
 'regularMarketChangePercent': 0.64779514,
 'regularMarketPrice': 495.63,
 'shortName': 'Microsoft Corporation',
 'longName': 'Microsoft Corporation',
 'fiftyTwoWeekLowChange': 146.43,
 'fiftyTwoWeekLowChangePercent': 0.41932985,
 'fiftyTwoWeekRange': '349.2 - 553.72',
 'fiftyTwoWeekHighChange': -58.089966,
 'fiftyTwoWeekHighChangePercent': -0.10490856,
 'fiftyTwoWeekChangePercent': -3.8283944,
 'dividendDate': 1788998400,
 'earningsTimestamp': 1785355200,
 'earningsTimestampStart': 1793217600,
 'earningsTimestampEnd': 1793217600,
 'earningsCallTimestampStart': 1785360600,
 'earningsCallTimestampEnd': 1785360600,
 'isEarningsDateEstimate': True,
 'epsTrailingTwelveMonths': 17.94,
 'epsForward': 23.57298,
 'epsCurrentYear': 19.75306,
 'priceEpsCurrentYear': 25.091303,
 'fiftyDayAverageChange': 41.961212,
 'fiftyDayAverageChangePercent': 0.09249306,
 'twoHundredDayAverageChange': 64.37247,
 'twoHundredDayAverageChangePercent': 0.14926688,
 'sourceInterval': 15,
 'exchangeDataDelayedBy': 0,
 'averageAnalystRating': '1.4 - Strong Buy',
 'corporateActions': [],
 'postMarketTime': 1789171170,
 'regularMarketTime': 1789156801,
 'displayName': 'Microsoft',
 'trailingPegRatio': 1.6096}

In [6]:
# get historical market data, here max is 35 years.
msft.history(period="max")

,Open,High,Low,Close,Volume,Dividends,Stock Splits
Date,,,,,,,
1986-03-13 00:00:00-05:00,0.053745,0.061649,0.053745,0.059014,1031788800,0.0,0.0
1986-03-14 00:00:00-05:00,0.059014,0.062176,0.059014,0.061122,308160000,0.0,0.0
1986-03-17 00:00:00-05:00,0.061122,0.062703,0.061122,0.062176,133171200,0.0,0.0
1986-03-18 00:00:00-05:00,0.062176,0.062703,0.060068,0.060595,67766400,0.0,0.0
1986-03-19 00:00:00-05:00,0.060595,0.061122,0.059014,0.059541,47894400,0.0,0.0
...,...,...,...,...,...,...,...
2026-09-04 00:00:00-04:00,510.000000,511.000000,499.359985,499.700012,18101800,0.0,0.0
2026-09-08 00:00:00-04:00,493.010010,495.190002,490.149994,493.950012,18882300,0.0,0.0
2026-09-09 00:00:00-04:00,493.070007,494.390015,489.799988,491.649994,12889600,0.0,0.0
2026-09-10 00:00:00-04:00,488.320007,494.519989,486.000000,492.440002,16038800,0.0,0.0
2026-09-11 00:00:00-04:00,495.649994,498.970001,492.579987,495.630005,14510500,0.0,0.0

In [8]:
msft.dividends

Date
2003-02-19 09:30:00-05:00    0.08
2003-10-15 09:30:00-04:00    0.16
2004-08-23 09:30:00-04:00    0.08
2004-11-15 09:30:00-05:00    3.08
2005-02-15 09:30:00-05:00    0.08
                             ...
2025-08-21 09:30:00-04:00    0.83
2025-11-20 09:30:00-05:00    0.91
2026-02-19 09:30:00-05:00    0.91
2026-05-21 09:30:00-04:00    0.91
2026-08-20 09:30:00-04:00    0.91
Name: Dividends, Length: 91, dtype: float64

In [10]:
msft.quarterly_balance_sheet

,2026-06-30,2026-03-31,2025-12-31,2025-09-30,2025-06-30,2025-03-31,2024-12-31
Ordinary Shares Number,7.427000e+09,7.429000e+09,7.428838e+09,7.433088e+09,7.434159e+09,NaN,NaN
Share Issued,7.427000e+09,7.429000e+09,7.428838e+09,7.433088e+09,7.434159e+09,NaN,NaN
Net Debt,1.935900e+10,8.157000e+09,1.596600e+10,1.435900e+10,1.290900e+10,NaN,NaN
Total Debt,5.682600e+10,5.696500e+10,5.760700e+10,6.055600e+10,6.058800e+10,NaN,NaN
Tangible Book Value,3.041270e+11,2.753810e+11,2.509640e+11,2.223430e+11,2.013660e+11,NaN,NaN
...,...,...,...,...,...,...,...
Cash Cash Equivalents And Short Term Investments,7.665100e+10,7.822800e+10,8.945600e+10,1.020050e+11,9.455500e+10,NaN,NaN
Other Short Term Investments,5.571600e+10,4.612300e+10,6.516000e+10,7.315600e+10,6.431300e+10,NaN,NaN
Cash And Cash Equivalents,2.093500e+10,3.210500e+10,2.429600e+10,2.884900e+10,3.024200e+10,NaN,NaN
Cash Equivalents,7.876000e+09,1.937400e+10,1.407500e+10,1.748300e+10,1.853100e+10,NaN,NaN
Cash Financial,1.305900e+10,1.273100e+10,1.022100e+10,1.136600e+10,1.171100e+10,NaN,NaN

In [11]:
msft.earnings_estimate

,avg,low,high,yearAgoEps,numberOfAnalysts,growth,currency
period,,,,,,,
0q,4.72455,4.43,4.83363,4.13000,25,0.1440,USD
+1q,4.82718,4.72,5.02000,4.14000,25,0.1660,USD
0y,19.75306,19.21,20.70000,17.28000,33,0.1431,USD
+1y,23.57298,20.93,26.00000,19.75306,33,0.1934,USD

In [12]:
msft.eps_trend

         current  7daysAgo  30daysAgo  60daysAgo  90daysAgo currency
period
0q       4.72455   4.72455    4.72036    4.62319    4.61418      USD
+1q      4.82718   4.82878    4.82335    4.78767    4.77702      USD
0y      19.75306  19.75306   19.72206   19.38938   19.37300      USD
+1y     23.57298  23.57328   23.55269   22.58739   22.62778      USD

In [13]:
msft.financials

,2026-06-30,2025-06-30,2024-06-30,2023-06-30
Tax Effect Of Unusual Items,1.110650e+09,-7.721784e+07,-1.000900e+08,-2.850000e+06
Tax Rate For Calcs,1.940000e-01,1.762960e-01,1.823130e-01,1.900000e-01
Normalized EBITDA,2.017940e+11,1.558830e+11,1.322290e+11,1.051550e+11
Total Unusual Items,5.725000e+09,-4.380000e+08,-5.490000e+08,-1.500000e+07
Total Unusual Items Excluding Goodwill,5.725000e+09,-4.380000e+08,-5.490000e+08,-1.500000e+07
Net Income From Continuing Operation Net Minority Interest,1.337490e+11,1.018320e+11,8.813600e+10,7.236100e+10
Reconciled Depreciation,3.853400e+10,2.943300e+10,2.095800e+10,1.386100e+10
Reconciled Cost Of Revenue,1.063740e+11,8.783100e+10,7.411400e+10,6.586300e+10
EBITDA,2.075190e+11,1.554450e+11,1.316800e+11,1.051400e+11
EBIT,1.689850e+11,1.260120e+11,1.107220e+11,9.127900e+10
Net Interest Income,2.500000e+08,2.620000e+08,2.220000e+08,1.026000e+09
Interest Expense,3.051000e+09,2.385000e+09,2.935000e+09,1.968000e+09
Interest Income,3.301000e+09,2.647000e+09,3.157000e+09,2.994000e+09
Normalized Income,1.291346e+11,1.021928e+11,8.858491e+10,7.237315e+10
Net Income From Continuing And Discontinued Operation,1.337490e+11,1.018320e+11,8.813600e+10,7.236100e+10
Total Expenses,1.766020e+11,1.531960e+11,1.356890e+11,1.233920e+11
Total Operating Income As Reported,1.552370e+11,1.285280e+11,1.094330e+11,8.852300e+10
Diluted Average Shares,7.453000e+09,7.465000e+09,7.469000e+09,7.472000e+09
Basic Average Shares,7.429000e+09,7.433000e+09,7.431000e+09,7.446000e+09
Diluted EPS,1.795000e+01,1.364000e+01,1.180000e+01,9.680000e+00
Basic EPS,1.800000e+01,1.370000e+01,1.186000e+01,9.720000e+00
Diluted NI Availto Com Stockholders,1.337490e+11,1.018320e+11,8.813600e+10,7.236100e+10
Net Income Common Stockholders,1.337490e+11,1.018320e+11,8.813600e+10,7.236100e+10
Net Income,1.337490e+11,1.018320e+11,8.813600e+10,7.236100e+10
Net Income Including Noncontrolling Interests,1.337490e+11,1.018320e+11,8.813600e+10,7.236100e+10
Net Income Continuous Operations,1.337490e+11,1.018320e+11,8.813600e+10,7.236100e+10
Tax Provision,3.218500e+10,2.179500e+10,1.965100e+10,1.695000e+10
Pretax Income,1.659340e+11,1.236270e+11,1.077870e+11,8.931100e+10
Other Income Expense,1.044700e+10,-5.163000e+09,-1.868000e+09,-2.380000e+08
Other Non Operating Income Expenses,4.722000e+09,-4.725000e+09,-1.319000e+09,-2.230000e+08
Special Income Charges,-1.780000e+08,-9.430000e+08,-2.060000e+08,-3.000000e+07
Write Off,1.780000e+08,9.430000e+08,2.060000e+08,3.000000e+07
Gain On Sale Of Security,5.903000e+09,5.050000e+08,-3.430000e+08,1.500000e+07
Net Non Operating Interest Income Expense,2.500000e+08,2.620000e+08,2.220000e+08,1.026000e+09
Interest Expense Non Operating,3.051000e+09,2.385000e+09,2.935000e+09,1.968000e+09
Interest Income Non Operating,3.301000e+09,2.647000e+09,3.157000e+09,2.994000e+09
Operating Income,1.552370e+11,1.285280e+11,1.094330e+11,8.852300e+10
Operating Expense,7.022800e+10,6.536500e+10,6.157500e+10,5.752900e+10
Research And Development,3.556200e+10,3.248800e+10,2.951000e+10,2.719500e+10
Selling General And Administration,3.466600e+10,3.287700e+10,3.206500e+10,3.033400e+10
Selling And Marketing Expense,2.671000e+10,2.565400e+10,2.445600e+10,2.275900e+10
General And Administrative Expense,7.956000e+09,7.223000e+09,7.609000e+09,7.575000e+09
Other Gand A,7.956000e+09,7.223000e+09,7.609000e+09,7.575000e+09
Gross Profit,2.254650e+11,1.938930e+11,1.710080e+11,1.460520e+11
Cost Of Revenue,1.063740e+11,8.783100e+10,7.411400e+10,6.586300e+10
Total Revenue,3.318390e+11,2.817240e+11,2.451220e+11,2.119150e+11
Operating Revenue,3.318390e+11,2.817240e+11,2.451220e+11,2.119150e+11

In [15]:
msft.cash_flow

,2026-06-30,2025-06-30,2024-06-30,2023-06-30,2022-06-30
Free Cash Flow,6.698700e+10,7.161100e+10,7.407100e+10,5.947500e+10,NaN
Repurchase Of Capital Stock,-2.227100e+10,-1.842000e+10,-1.725400e+10,-2.224500e+10,NaN
Repayment Of Debt,-3.000000e+09,-3.216000e+09,-2.907000e+10,-2.750000e+09,NaN
Issuance Of Debt,0.000000e+00,0.000000e+00,2.439500e+10,0.000000e+00,NaN
Issuance Of Capital Stock,2.009000e+09,2.056000e+09,2.002000e+09,1.866000e+09,NaN
Capital Expenditure,-1.159480e+11,-6.455100e+10,-4.447700e+10,-2.810700e+10,NaN
End Cash Position,2.093500e+10,3.024200e+10,1.831500e+10,3.470400e+10,NaN
Beginning Cash Position,3.024200e+10,1.831500e+10,3.470400e+10,1.393100e+10,NaN
Effect Of Exchange Rate Changes,-1.960000e+08,6.300000e+07,-2.100000e+08,-1.940000e+08,NaN
Changes In Cash,-9.111000e+09,1.186400e+10,-1.617900e+10,2.096700e+10,NaN
Financing Cash Flow,-5.254600e+10,-5.169900e+10,-3.775700e+10,-4.393500e+10,NaN
Cash Flow From Continuing Financing Activities,-5.254600e+10,-5.169900e+10,-3.775700e+10,-4.393500e+10,NaN
Net Other Financing Charges,-2.839000e+09,-2.291000e+09,-1.309000e+09,-1.006000e+09,NaN
Cash Dividends Paid,-2.644500e+10,-2.408200e+10,-2.177100e+10,-1.980000e+10,NaN
Common Stock Dividend Paid,-2.644500e+10,-2.408200e+10,-2.177100e+10,-1.980000e+10,NaN
Net Common Stock Issuance,-2.026200e+10,-1.636400e+10,-1.525200e+10,-2.037900e+10,NaN
Common Stock Payments,-2.227100e+10,-1.842000e+10,-1.725400e+10,-2.224500e+10,NaN
Common Stock Issuance,2.009000e+09,2.056000e+09,2.002000e+09,1.866000e+09,NaN
Net Issuance Payments Of Debt,-3.000000e+09,-8.962000e+09,5.750000e+08,-2.750000e+09,NaN
Net Short Term Debt Issuance,0.000000e+00,-5.746000e+09,5.250000e+09,0.000000e+00,NaN
Short Term Debt Issuance,NaN,NaN,5.250000e+09,0.000000e+00,0.0
Net Long Term Debt Issuance,-3.000000e+09,-3.216000e+09,-4.675000e+09,-2.750000e+09,NaN
Long Term Debt Payments,-3.000000e+09,-3.216000e+09,-2.907000e+10,-2.750000e+09,NaN
Long Term Debt Issuance,0.000000e+00,0.000000e+00,2.439500e+10,0.000000e+00,NaN
Investing Cash Flow,-1.395000e+11,-7.259900e+10,-9.697000e+10,-2.268000e+10,NaN
Cash Flow From Continuing Investing Activities,-1.395000e+11,-7.259900e+10,-9.697000e+10,-2.268000e+10,NaN
Net Other Investing Changes,-1.986100e+10,2.317000e+09,-1.298000e+09,-3.116000e+09,NaN
Net Investment Purchase And Sale,-1.948000e+09,-4.387000e+09,1.793700e+10,1.021300e+10,NaN
Sale Of Investment,5.640300e+10,2.538800e+10,3.566900e+10,4.786400e+10,NaN
Purchase Of Investment,-5.835100e+10,-2.977500e+10,-1.773200e+10,-3.765100e+10,NaN
Net Business Purchase And Sale,-1.743000e+09,-5.978000e+09,-6.913200e+10,-1.670000e+09,NaN
Purchase Of Business,-1.743000e+09,-5.978000e+09,-6.913200e+10,-1.670000e+09,NaN
Net PPE Purchase And Sale,-1.159480e+11,-6.455100e+10,-4.447700e+10,-2.810700e+10,NaN
Purchase Of PPE,-1.159480e+11,-6.455100e+10,-4.447700e+10,-2.810700e+10,NaN
Operating Cash Flow,1.829350e+11,1.361620e+11,1.185480e+11,8.758200e+10,NaN
Cash Flow From Continuing Operating Activities,1.829350e+11,1.361620e+11,1.185480e+11,8.758200e+10,NaN
Change In Working Capital,-4.895000e+09,-5.350000e+09,1.824000e+09,-2.388000e+09,NaN
Change In Other Working Capital,7.486000e+09,5.400000e+09,7.035000e+09,5.177000e+09,NaN
Change In Other Current Liabilities,2.140000e+09,4.947000e+09,5.616000e+09,2.825000e+09,NaN
Change In Other Current Assets,-6.591000e+09,-5.994000e+09,-8.465000e+09,-4.824000e+09,NaN
Change In Payables And Accrued Expense,5.268000e+09,5.690000e+08,3.545000e+09,-2.721000e+09,NaN
Change In Payable,5.268000e+09,5.690000e+08,3.545000e+09,-2.721000e+09,NaN
Change In Account Payable,5.268000e+09,5.690000e+08,3.545000e+09,-2.721000e+09,NaN
Change In Tax Payable,NaN,NaN,1.687000e+09,-3.580000e+08,696000000.0
Change In Income Tax Payable,NaN,NaN,1.687000e+09,-3.580000e+08,696000000.0
Change In Inventory,-4.610000e+08,3.090000e+08,1.284000e+09,1.242000e+09,NaN
Change In Receivables,-1.273700e+10,-1.058100e+10,-7.191000e+09,-4.087000e+09,NaN
Changes In Account Receivables,-1.273700e+10,-1.058100e+10,-7.191000e+09,-4.087000e+09,NaN
Stock Based Compensation,1.240500e+10,1.197400e+10,1.073400e+10,9.611000e+09,NaN
Unrealized Gain Loss On Investment Securities,NaN,-5.360000e+08,-1.460000e+08,-3.030000e+08,-509000000.0
Asset Impairment Charge,NaN,9.430000e+08,2.060000e+08,3.000000e+07,101000000.0
Deferred Tax,1.418900e+10,-7.056000e+09,-4.738000e+09,-6.059000e+09,NaN
Deferred Income Tax,1.418900e+10,-7.056000e+09,-4.738000e+09,-6.059000e+09,NaN
Depreciation Amortization Depletion,3.853400e+10,2.943300e+10,2.095800e+10,1.386100e+10,NaN
Depreciation And Amortization,3.853400e+10,2.943300e+10,2.095800e+10,1.386100e+10,NaN
Depreciation,3.853400e+10,2.943300e+10,2.095800e+10,1.386100e+10,NaN
Operating Gains Losses,-1.104700e+10,5.329000e+09,1.634000e+09,4.690000e+08,NaN
Gain Loss On Investment Securities,NaN,2.020000e+08,2.450000e+08,4.690000e+08,-1000000.0
Net Income From Continuing Operations,1.337490e+11,1.018320e+11,8.813600e+10,7.236100e+10,NaN